LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional

LOCAL_MODULE := Kika-Keyboard_com.iqqijni.bbkeyboard

LOCAL_CERTIFICATE := PRESIGNED

LOCAL_SRC_FILES := Kika-Keyboard_KIkaInput

LOCAL_MODULE_CLASS := APPS

LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)

include $(BUILD_PREBUILT)
